gnodeb:
  controlif:
    ip: tester.my5g.org
    port: 9487
  dataif:
    ip: tester.my5g.org
    port: 2152
  plmnlist:
    mcc: "208"
    mnc: "93"
    tac: "000001"
    gnbid: "000002"
  slicesupportlist:
    st: "01"
    sst: "010203"
ue:
  imsi: "imsi-2089300000001"
  key: "70d49a71dd1a2b806a25abe0ef749f1e"
  opc: "6f1bf53d624b3a43af6592854e2444c7"
  amf: "8000"
  hplmn:
    mcc: "208"
    mnc: "93"
  snssai:
    sd: 1
    sst: "010203"
amfif:
  ip: amf.free5gc.org
  port: 38412
  name: "free5gc"